import './globals.css'
import { Inter } from 'next/font/google'
import Document from './pages/_document'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Online Shoe Store',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
      <Document/>
    </html>
  )
}
