import {inter} from "./fonts";
import './globals.css'

export const metadata = {
  title: 'Online Shoe Store',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.variable} font-inter`}>{children}</body>
    </html>
  )
}
